[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.76"
tonic = "0.10.2"
sdk ={path = "../sdk"}
tokio = "1.35.1"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
tracing = "0.1.40"
sea-orm = "0.12.10"
log = "0.4.20"
