#!/bin/sh
FROM rust
RUN apt-get update

RUN cargo install cargo-watch

ARG name=posts
ARG config=123
ARG service_token=0000
ARG port=5151
ARG environment=development

# shellcheck disable=SC2154
ENV CONFIG="${config}"
# shellcheck disable=SC2154
ENV SERVICE_TOKEN="${service_token}"
# shellcheck disable=SC2154
ENV NAME="${name}"
# shellcheck disable=SC2154
ENV PORT="${port}"
# shellcheck disable=SC2154
ENV ENVIRONMENT="${environment}"

COPY sdk /app/backend/sdk

WORKDIR /app/backend/posts

COPY posts/Cargo.toml /app/backend/posts/Cargo.toml
COPY posts/Cargo.lock /app/backend/posts/Cargo.lock

RUN apt-get install -y protobuf-compiler

COPY posts /app/backend/posts

RUN cargo build

CMD ["cargo", "watch", "-c", "-w", "src", "-x", "run --bin=main"]

EXPOSE "$PORT"
