#!/bin/sh
FROM rust:latest
RUN apt-get update

RUN cargo install cargo-watch

ARG name=reactions
ARG config=123
ARG service_token=0000
ARG port=5050
ARG environment=development

# shellcheck disable=SC2154
ENV CONFIG="${config}"
# shellcheck disable=SC2154
ENV SERVICE_TOKEN="${service_token}"
# shellcheck disable=SC2154
ENV NAME="${name}"
# shellcheck disable=SC2154
ENV PORT="${port}"
# shellcheck disable=SC2154
ENV ENVIRONMENT="${environment}"

COPY sdk /app/backend/sdk

WORKDIR /app/backend/reactions

COPY reactions/Cargo.toml /app/backend/reactions/Cargo.toml
COPY reactions/Cargo.lock /app/backend/reactions/Cargo.lock

RUN apt-get install -y protobuf-compiler

COPY reactions /app/backend/reactions

RUN cargo build

CMD ["cargo", "watch", "-c", "-w", "src", "-x", "run --bin=main"]

EXPOSE "$PORT"
